server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CorporateDB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true